### ISSUE TITLE
Inconsistency in names for PageUp and PageDn

### ISSUE THREAD

**Issue by rickyweb** [bfritscher/carnac#43]
The keys on the computer are called "pgup" and "pgdn", but on screen you see "PageUp" and "Next". Users seeing "Next" can't understand that I used the "pgdn" key, more so if "pgup" is not called "Previous" but correctly "PageUp".

**Comment by mawdesign** [comment]
The is a fix in another fork: https://github.com/doggy8088/carnac/commit/11ab04e91437f3256c0b7bf84602a329d9b33830

**Comment by mawdesign** [comment]
Meanwhile, the following yml file will at least also say PageDown (still has Next though):
```
group:          
process:        

shortcuts:
    - name: PageDown
      keys:
      - PageDown
```
