### ISSUE TITLE
Shift + keypress when using keymap file only shows after 2nd press

### ISSUE THREAD

**Issue by ghost** [bfritscher/carnac#46]
Using the latest beta release, it appears as though the tool does not properly show keypresses that are combined with the shift button. For example, if I create a sample keymap file like this:

```
group: Fubar
process:        

shortcuts:
    - name: Run
      keys:
      - Shift+R
```

and I try pressing SHIFT+R, nothing appears on the popup / overlay. However, if I hold down the shift button and press the R button twice, then the popup will appear but only the one time.
